### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by MathiasHobler** [MathiasHobler/capstone-project#11]
## User Story

As a User
I want to have a calendar
so that I can see upcoming events

## AC

- [ ] my upcoming events should be highlighted in the calendar view

- [ ] days with upcoming events are clickable and link to the details page 

- [ ] back button to Home Screen

## Design
<img width="218" alt="Bildschirmfoto 2022-06-21 um 16 03 26" src="https://user-images.githubusercontent.com/44622193/174822965-dd227d66-1269-4342-9d43-5b36ec40205e.png">

## Task

- [ ] create new branch
- [ ] install react-calendar library 
- [ ] create calender component

- [ ] writing tests

## Complexity
L

**Comment by PhilippDemmelmair** [comment]
Hey, 

will the data in the calendar be dummy data to start with it or do you need a function to load that dates? Also are there more steps needed in the creating calendar component task? I especially think about the displayed days with upcoming events, the go to details page part and the return button. Since these are AC for your user story, they should also be represented by an own task I think.
