### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#23]
## User Story

As a User
I want to have a nice layout
so that I have fun to use the application

## AC

- [x] my upcoming events should be highlighted in the calendar view

- [x] days with upcoming events are clickable and link to the details page

- [x] back button to Home Screen

## Design

<img width="710" alt="Bildschirmfoto 2022-06-29 um 12 05 16" src="https://user-images.githubusercontent.com/103875201/176410730-674a0d33-c985-4119-a87d-00313bd2b221.png">

## Task

- [x] create new branch
- [x] install react-calendar library
- [x] create calender component

- [x] writing tests

## Complexity

L
