### ISSUE TITLE
Formvalidation

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#24]
## Developer Story

As a Developer
I want to valid the form
so that I will get valid inputs

## AC

- [ ] all inputs should have the correct types
- [ ] if input is not correct, there should be messages

## Design

/

## Task

- [ ] create new branch
- [ ] check type of every input
- [ ] create display error message in span for unexpected input

## Complexity

S
