### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#25]
## User Story

As a User
I want to registrate me
so that I can have a own account

## AC

- [ ] User should be created in database

- [ ] Password should be hashed, security

## Design

<img width="218" alt="" src="">

## Task

- [ ] create new branch
- [ ] install bcrypt
- [ ] create user-model
- [ ] create register component
- [ ] create the register-form
- [ ] connect register to database

## Complexity

L (with option to xl :-P)
