### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#26]
## User Story

As a User
I want to login
so that I can use the application-features

## AC

- [ ] User should be able to login
- [ ] If login is successfully, show events

## Design

<img width="384" alt="Screenshot 2022-06-29 at 12 10 04" src="https://user-images.githubusercontent.com/44622193/176411788-fd09f6cb-85bf-44fc-aa40-bb88e6a24454.png">

## Task

- [ ] create new branch
- [ ] create login-component
- [ ] check, if user is registrated
- [ ] use session-storage

## Complexity

L
