### ISSUE TITLE
Eventhandling

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#27]
## User Story

As a User
I want to handle my events
so that just I can edit and delete them

## AC

- [ ] Only the event-owner can edit and delete it's own event

## Design

<img width="218" alt="" src="">

## Task

- [ ] create new branch
- [ ] at create, save user-id in author-key on event
- [ ] check on detail, if user is eventowner
- [ ] if true, toggle edit/delete buttons

## Complexity

L-XL
