### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#29]
## User Story

As a User
I want to have a bookmark-function
so that I find them again

## AC

- [x] The events should have a button to bookmark

- [x] The bookmarked events should be shown on a seperate site

- [x] The bookmark site should be availble by navbar

## Design

Take a look on Homescreen

## Task

- [x] create new branch
- [x] create a new component named bookmark
- [x] create a bookmark button in eventcard
- [x] render all bookmarked events in bookmark-component
- [ ] writing tests

## Complexity

L

**Comment by PhilippDemmelmair** [comment]
Looks fine
