### ISSUE TITLE
Create

### ISSUE THREAD

**Issue by MathiasHobler** [MathiasHobler/capstone-project#3]
## UserStory

As a user
I want to create an event
so that everyone can see

## AC

- [x]  Input-field for: date, time, name, discription
- [x] Checkboxes for categories
- [x] Submit-button

## Design

<img width="218" alt="Bildschirmfoto 2022-06-21 um 15 00 26" src="https://user-images.githubusercontent.com/103875201/174805862-56974299-cb95-422f-aef6-ad6eb78d709f.png">

## Tasks

- [x]  Create a new branch
- [x] Create a form-component
- [x] Add a form with input for:  Title, date/time, adress, description, required, entry
- [x] Add basic tests

## Complexity

Medium
