### ISSUE TITLE
Animated background

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#30]
## User Story

As a developer
I want to create a animated background
so that the effects of all other components are visible

## AC

- [ ] The background should have a dark ground color

- [ ] The animated elements should have bright and diffrent colors

- [ ] The elements should run from bottom to the top slowly

## Task

- [ ] create new branch
- [ ] create a new component named background
- [ ] style the background-component

## Complexity

L

**Comment by PhilippDemmelmair** [comment]
Looks also fine
