### ISSUE TITLE
Participation

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#31]
## User Story

As a User
I want to have a participate-function
so that I can participate in the event

## AC

- [ ] The events should have a button to participate

- [ ] The participate events should be shown on a seperate site

- [ ] The participate events should be availble by navbar

## Design

Take a look on Homescreen

## Task

- [ ] create new branch
- [ ] create a new component named participate
- [ ] create a participate button in eventcard
- [ ] render all participation events in participate-component
- [ ] writing tests

## Complexity

L

**Comment by PhilippDemmelmair** [comment]
Looks pretty fine, if I understand it correctly. Maybe you should take care of the spelling. Will there be shown the events a user participates in, like a bookmark, or the events that he has the possibility to participate, eg a list of upcoming events. As of now, like you write it here, this is a bit unclear.

**Comment by MathiasHobler** [comment]
have rephrased it, hope it is now more understandable

**Comment by PhilippDemmelmair** [comment]
would suggest to change "all participation events" to "all events a user participates in" but besides that it looks fine
