### ISSUE TITLE
Custom Button

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#35]
## User Story

As a Developer
I want to built a custom button component
so that the same styled button is useable in the whole application

## AC

- [ ] The button should have the same optical styling like the navbar and the events

- [ ] The styled button should be used in the whole application

## Design

<img width="402" alt="Screenshot 2022-07-05 at 16 15 11" src="https://user-images.githubusercontent.com/103875201/177350386-f878cfb7-60b5-4269-b17d-2da562ca1ae4.png">

## Task

- [ ] create new branch
- [ ] create a button component
- [ ] style button component
- [ ] implement button

- [ ] writing tests

## Complexity

M
