### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#36]
## User Story

As a User
I want to upload a picture
so that I can use my own event-picture

## AC

- [ ] In the create form should be a possibility to upload a image file

- [ ] The Image shuold be saved in the database

- [ ] The Image should be shown in the event card

## Task

- [ ] create new branch
- [ ] implement upload-function in form component
- [ ] implement uploaded image in event card

## Complexity

L

**Comment by p-enz** [comment]
looks good to me, curious to see your own event pictures soon
