### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#37]
## User Story

As a User
I want to have categories
so that I can filter all events

## AC

- [ ] In the create form should be categories to choose

- [ ] In the header should be filter-buttons for the home screen

## Design

<img width="663" alt="Bildschirmfoto 2022-07-05 um 16 42 45" src="https://user-images.githubusercontent.com/103875201/177355226-f8dfd1f2-acf5-4162-8c46-eef2644bda08.png">

## Task

- [ ] create new branch
- [ ] create filter in event form
- [ ] create filter reel
- [ ] implement filtering on home screen

- [ ] writing tests

## Complexity

L
