### ISSUE TITLE
As a Developer

### ISSUE THREAD

**Issue by MathiasHobler** [MathiasHobler/capstone-project#39]
As a Developer
I want to refactor the details component, 
so that it is easier to implement new Features in the details view

## AC

- [ ] Design should match the App Design

- [ ] Content on Details Card should be scrollable

- [ ]  show more Details 

## Task

- [ ] create new git branch

- [ ] refactor the Details component

## Complexity
M
