### ISSUE TITLE
Read

### ISSUE THREAD

**Issue by MathiasHobler** [MathiasHobler/capstone-project#4]
## UserStory

As a user 
I want to information about a event
so that can get informed about the details

## AC
- [x] user can see a event

## Design
<img width="825" alt="Bildschirmfoto 2022-06-20 um 16 45 45" src="https://user-images.githubusercontent.com/44622193/174627559-fefd0cdb-cc86-41f5-a0c9-f680ca6ccb72.png">

## Task

- [x] create a new branch
- [x] create component event 
- [x] create array with dummy events
- [x] create event model
