### ISSUE TITLE
## User Story

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#44]
As a User
I want to have a map-function
so that I can get navigated to the location

## AC

- [ ] A map should be shown on event-details

- [ ] On tapping the map should open

- [ ] The map should have a navigation function

## Design

Take a look on our i-frame on detail-page

## Task

- [ ] create new branch
- [ ] look for fitting api
- [ ] implement in create und detail page
- [ ] writing tests

## Complexity

L
