### ISSUE TITLE
App-styling

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#47]
## User Story

As a user
I want a consistent user interface
so that I have a positive user experience

## AC

- [] The design should enthusiastic the user even without interaction
- [] The app should have a uniform color design
- [] The app should appear professional and high quality
- [] The user should have fun while using the app
- [] The user should be able to navigate intuitively through the app

## Task

- [ ] create new branch
- [ ] Agree on a style for buttons, head component, foot component, detail component, create component, bookmark component
- [ ] Control and style all components

## Complexity

L

**Comment by JessicaLoers** [comment]
👍
