### ISSUE TITLE
Reel-refactoring

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#48]
## User Story

As a Developer
I want to refactor the reel code
so that I can get a more use- and readable code

## AC

- [ ]  The code should become shorter
- [ ] The code should become more readable
- [ ]  The code should become more reusable

## Task

- [ ] create new branch
- [ ] create a array of objects
- [ ] fill the array with icon and meta-data
- [ ] create a map function with return for each object in array

## Complexity

M

**Comment by JessicaLoers** [comment]
**Hallöchen @Falconiac @MathiasHobler  👋**
**AC** - I think there're some more like...
- the code of 120 lines should get about 50% shorter... **but still works** 😁

**Comment by Falconiac** [comment]
Hey @JessicaLoers ,
I have unformulated the AC, I hope it fits like this...
