### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by MathiasHobler** [MathiasHobler/capstone-project#6]
This userstory is following #3 , the create-page

## User Story
As a user
I want to navigate 
so that I can see different pages

## AC
- [x] Navigation should include links to Home and Create
- [x] Navigation should be permanently visible at the bottom of every page.
- [x] Navigation should appear as icons within a frame

## Design

<img width="577" alt="Bildschirmfoto 2022-06-20 um 16 57 23" src="https://user-images.githubusercontent.com/44622193/174629891-36a8e7ad-62de-4de2-8694-a0a3ff78af86.png">

## Task
- [x] create new branch
- [x]  install materialUi icons
- [x] create navbar component
- [x] use material icons for links to the pages
- [x] fix positon on bottom
- [x] add routing path
- [x] testing-navigation-with-react-testing-library
- [ ] add navigation to storybook

## Complexity
S

**Comment by JessicaLoers** [comment]
**Hello Mathias, Hello Falco!** 

I have some comments you may think about before moving further.
Think of a user story as a "finished product" – always have a running app with a user benefit. In this version of your app you have neither a create page nor a create form. You should avoid linking to "empty pages".


 **Value proposition:** Perhaps you could describe it the purpose of this feature more detailed.  Why she/he needs this feature?.
_For example:_
As a user
I want to have a navigation
So that I can access page/pages XY


**Acceptance Criteria:** Perhaps you could describe it more detailed. What does she/he 
_For example:_ 
The navigation should include link/links XY 
The navigation should be always visible on the bottom on the "each page"
The navigation should be displayed as icons

**Tasks:** Perhaps you could describe it more detailed
_For example_ 
   - Create new branch
   - Create new component Navigation
   - Implement React Router
   -  ...
  
- You can also add storybook and testing as tasks if you plan to implement 
- Please add the Complexity of your feature. Rate in T-Shirt sizes: XS, S, M, L, XL

**In general:** 

- There is a lost k in your User Story
- There are some markdown formatting issues in your User Story (e.g. Headlines, 
- For your own workflow you could transform your bullet points in checkboxes by writing "- [ ]". This could be helpful to get an overview about the criteria or tasks that are not fulfilled yet.

**If you have any question, feel free to ask** 🙂
