### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Falconiac** [MathiasHobler/capstone-project#8]
## UserStory

As a user
I want to update my event
so that I can share changes on my event

##  AC
- [ ] On button click, the user is able to reopen his event in editor

- [ ]  In the editor the user can make changes on his event an save them
 

##  Design

<img width="497" alt="editbtn" src="https://user-images.githubusercontent.com/103875201/174747813-532b7b2e-5b1c-4901-bbdc-6146546cc78f.png">

## Task

- [ ] create a new branch

- [ ] create a edit-button in event-component

- [ ]  add onClick-event for reopening the event in create-component
