### ISSUE TITLE
MongoDb

### ISSUE THREAD

**Issue by MathiasHobler** [MathiasHobler/capstone-project#9]
## Dev Story

As a developer
I want to add a database
so that I can store all data in there

## AC

- [x]  connection to mongodb established

- [x]  event collection created

- [ ]  Crud functionality 

## Design

<img width="924" alt="Screenshot 2022-06-21 at 12 05 08" src="https://user-images.githubusercontent.com/44622193/174774340-9a93460c-fccf-42b6-9cb4-82e555e59e28.png">

## Task

- [x] create new branch

- [x] install mongoosjs

- [x] create mongodb collection
- [x] create mongoose schema event

- [x] establish connection to mongoose collection

- [x] implement basic CRUD

- [x] testing api with postman

## Complexity
M

**Comment by mbosselmann** [comment]
Hi Mathias and Falco,
good job! 👍 I just have two nit-picking remarks: 
- a typo: "connection to mongo**l**db established" - you should remove the `l`
- and about your value proposition: you could also write your story from a user perspective and could refer to the possibility to see the data from multiple devices. Something that could also be checked via quality assurance. 

An example for the value proposition could be:

As a user
I need to save my events in a database
to be able to access my events from anywhere

Just think about it and decide for yourselves if you want to rewrite the user story. :)
